### ISSUE TITLE
Decoder Cache Index cannot acquire lock

### ISSUE THREAD

**Issue by arnav-gudibande** [nengo/nengo#1105]
This issue occurs when I try to run a project. The project still runs but takes significantly more time to compile.

`py:139: UserWarning: Decoder cache index could not acquire lock. Cache index was not synced.
  "Decoder cache index could not acquire lock. "
Exception AttributeError: "'CacheIndex' object has no attribute '_updates'" in <bound method CacheIndex.__del__ of <nengo.cache.CacheIndex object at 0x7f15daaceb10>> ignored
`

Running on Ubuntu 14.04 LTS

**Comment by jgosmann** [comment]
What is the exact Nengo version you are running?

This is probably related to #1048  which has been fixed with PR #1053 that will be released as part of Nengo 2.1.1. (I hope that release happens soon, @tbekolay.)

Note that even after updating to 2.1.1, manual intervention will be necessary to allow the cache to operate normally again. If you are using Linux, you have to delete the file `~/.cache/nengo/decoders/index.lock`. If you are not using Linux, let me know what you are using and I can find out what the equivalent file is.

**Comment by arnav-gudibande** [comment]
@jgosmann Thanks! The update was not necessary; I just deleted the lock file and it is working fine now. I am using Nengo 2.1.0 btw.

**Comment by jgosmann** [comment]
> The update was not necessary; I just deleted the lock file and it is working fine now.

True, but the problem might appear again without the update. But now you know what to do. :)

**Comment by jgosmann** [comment]
I'm closing the issue as Nengo 2.1.1 has been released. Feel free to reopen it if you encounter the issue again.
